package com.dodax.jobs;

/**
 * Job for exception generation after the specified delay
 */
public class SomeExceptionJob implements IJob {

  private final int delayInMs;

  /**
   * Constructs SomeExceptionJob with specified delay
   *
   * @param delayInMs delay time in milliseconds
   */
  public SomeExceptionJob(final int delayInMs) {
    this.delayInMs = delayInMs;
  }

  @Override
  public void execute() {
    try {
      Thread.sleep(this.delayInMs);
      throw new RuntimeException("Exception generated by SomeExceptionJob");
    } catch (InterruptedException ignore) {
    }
  }
}
